### ISSUE TITLE
Strange input result

### ISSUE THREAD

**Issue by IgorErin** [PeanutProver/PeanutProver#17]
It seems like input result almost incomplete
```
PP: def f(x, y, z) z + y = x
PP: eval f(3, 1,2)
var: "x"
var: "y"
var: "z"
val: ['1'; '1'; '0']
val: ['1'; '0'; '1']
Error: The lists had different lengths.
```

**Comment by WoWaster** [comment]
I investigated with code from #18 and found that current solution makes vectors of numbers from input using `Seq.transpose` and that's why you have this error

**Comment by IgorErin** [comment]
Yes, there is one vector less. I didn't even get to the order

**Comment by IgorErin** [comment]
3 parameters, 2 arguments. Or am I doing something wrong. Need tests on the CLI...

**Comment by IgorErin** [comment]
I understood. Do we have them written in columns? Then everything is clear, okay
